[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
gas_price = 400000000
priority_gas_price = 400000000

# Gas reporting
gas_reports = ["*"]

# RPC endpoints
[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
amoy= "${AMOY_RPC_URL}"
hedera="${HEDERA_RPC_URL}"
OG="${OG_RPC_URL}"


# Etherscan verification
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
amoy = { key = "${POLYGONSCAN_API_KEY}"}
hedera={key="${HEDERASCAN_API_KEY}",url="https://api.hedera.com/api"}
